import { Toaster } from 'react-hot-toast';

import { Inter } from 'next/font/google';

import LoginModal from '@/components/modal/LoginModal';
import Modal from '@/components/modal/Modal';
import RegisterModal from '@/components/modal/RegisterModal';
import Navbar from '@/components/navbar/Navbar';

import getCurrentUser from './actions/getCurrentUser';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <RegisterModal />
        <LoginModal />
        <Toaster />
        <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
